version: 2
jobs:
  # Executing tests (by benefiting from caching)
  tests:
    docker:
      - image: circleci/python:3.7
    parallelism: 2
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local
      - restore_cache:
          keys:
            - tests-v1-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum ".circleci/config.yml" }}
      - run: .circleci/prepare.sh
      - run: ./run_tests.sh
      - save_cache:
          paths:
            - /usr/local/lib/python3.7/site-packages
            - /usr/local/bin
          key: tests-v1-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum ".circleci/config.yml" }}

  # Fetching the build infos to prepare the container build
  get-build-infos:
    docker:
      - image: habx/devops-build-infos
    working_directory: /work
    steps:
      - checkout
      - run: /build/run.sh
      - persist_to_workspace:
          root: /work
          paths:
            - version.txt
            - package.json
            - build.json

  # Building the container and uploading it
  build-container:
    docker:
      - image: plugins/ecr:17.05
    working_directory: /work
    steps:
      - checkout
      - attach_workspace:
          at: /work
      - run: ls -lh
      - setup_remote_docker:
          docker_layer_caching: true
      - run: .circleci/build-container.sh

  trigger-batch-execution:
    docker:
      - image: alpine
    working_directory: /work
    steps:
      - attach_workspace:
          at: /work
      - run: .circleci/trigger-batch-execution.sh

  # Publishing the the tasks
  deploy-to-kubernetes-standard-worker:
    docker:
      - image: quay.io/honestbee/drone-kubernetes
    working_directory: /work
    steps:
      - checkout
      - attach_workspace:
          at: /work
      - run:
          command: .circleci/deploy-to-kubernetes.sh
  deploy-to-kubernetes-low-priority-worker:
    docker:
      - image: quay.io/honestbee/drone-kubernetes
    working_directory: /work
    steps:
      - checkout
      - attach_workspace:
          at: /work
      - run:
          command: |
            export PLUGIN_DEPLOYMENT_POSTFIX=-low-priority
            .circleci/deploy-to-kubernetes.sh

workflows:
  version: 2
  ci-process:
    jobs:
      - get-build-infos:
          filters:
            tags:
              only: /^v.*/

      - tests:
          filters:
            tags:
              only: /^v.*/

      - build-container:
          context: default_env_vars
          requires:
            - get-build-infos
          filters:
            tags:
              only: /^v.*/
            # branches:
            #   only:
            #     - dev
            #     - feature/OPT-47-correct

      - trigger-batch-execution:
          context: default_env_vars
          requires:
            - get-build-infos
          filters:
            tags:
              only: /^v.*/

      - deploy-to-kubernetes-standard-worker:
          context: default_env_vars
          requires:
            - build-container
            - tests
          filters:
            tags:
              only: /^v.*/
            branches:
              only:
                - dev
                - feature/OPT-47-correct

      - deploy-to-kubernetes-low-priority-worker:
          context: default_env_vars
          requires:
            - build-container
            - tests
          filters:
            tags:
              only: /^v.*/
            branches:
              only:
                - dev
                - feature/OPT-47-correct
