version: 2
jobs:
  # Tests can benefit from standard caching
  tests:
    docker:
      - image: circleci/python:3.6
    parallelism: 2
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local
      - restore_cache:
          keys:
            - tests-v1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run: .circleci/prepare.sh
      # - run: ./run_tests.sh
      - save_cache:
          paths:
            - /usr/local/lib/python3.6/site-packages
            - /usr/local/bin
          key: tests-v1-{{ .Branch }}-{{ checksum "requirements.txt" }}

  # We're fetching the build infos
  get-build-infos:
    docker:
      - image: habx/devops-build-infos
    working_directory: /work/env
    steps:
      - checkout
      - run: /build/run.sh
      - persist_to_workspace:
          root: /work/env
          paths:
            - version.txt
            - package.json
            - build.json

  build-container:
    docker:
      - image: plugins/ecr:17.05
    working_directory: /work
    steps:
      - checkout
      - attach_workspace:
          at: /work
      - run: ls -lh
      - setup_remote_docker:
          docker_layer_caching: true
      - run: .circleci/build-container.sh

  deploy-to-kubernetes-standard-worker:
    docker:
      - image: quay.io/honestbee/drone-kubernetes
    steps:
      - checkout
      - run:
          command: .circleci/deploy-to-kubernetes.sh

  deploy-to-kubernetes-low-priority-worker:
    docker:
      - image: quay.io/honestbee/drone-kubernetes
    steps:
      - checkout
      - run:
          command: |
            export PLUGIN_DEPLOYMENT_POSTFIX=-low-priority
            .circleci/deploy-to-kubernetes.sh

workflows:
  version: 2
  ci-process:
    jobs:
      - get-build-infos
      - tests:
          filters:
            tags:
              only: /^v.*/

      - build-container:
          context: default_env_vars
          requires:
            - get-build-infos
      #          filters:
      #            tags:
      #              only: /^v.*/
      #            branches:
      #              only:
      #                - dev

      - deploy-to-kubernetes-standard-worker:
          context: default_env_vars
          requires:
            - build-container
            - tests
      #          filters:
      #            tags:
      #              only: /^v.*/
      #            branches:
      #              only:
      #                - dev

      - deploy-to-kubernetes-low-priority-worker:
          context: default_env_vars
          requires:
            - build-container
            - tests
#          filters:
#            tags:
#              only: /^v.*/
#            branches:
#              only:
#                - dev
