version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.6
    parallelism: 4
    steps:
      - checkout
      - run: env
      - run: ./run_tests.sh
workflows:
  version: 2
  test:
    jobs:
      - test
