version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.6
    parallelism: 4
    steps:
      - checkout
      - run: env
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - run: ./run_tests.sh
workflows:
  version: 2
  test:
    jobs:
      - test
