version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.6
    parallelism: 4
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ .Branch }}-{{ checksum "requirements.txt" }}
            - v1-dependencies-{{ .Branch }}
            - v1-dependencies
      - run: sudo chown -R circleci:circleci /usr/local
      - run: ./run_tests.sh
      - save_cache:
          paths:
            - /usr/local/lib/python3.6/site-packages
          key: v1-dependencies-{{ .Branch }}-{{ checksum "requirements.txt" }}
workflows:
  version: 2
  test:
    jobs:
      - test
