version: 1
update_configs:
  - package_manager: "python"
    directory: "/"
    update_schedule: "live"
    version_requirement_updates: "auto"
    automerged_updates:
      - match:
          dependency_type: "development"
          update_type: "semver:minor"
      - match:
          dependency_type: "production"
          update_type: "semver:minor"
  - package_manager: "docker"
    directory: "/"
    update_schedule: "daily"
